# aws-config/environment/dev.yaml

name: dev

# The Git repo and branch where this account's config should be pulled from
config_repo: https://github.com/tstrall/aws-config.git
config_branch: dev

# The Terraform module source repo for this environment
iac_repo: https://github.com/tstrall/aws-iac.git
iac_strict: true  # Set to false to allow components to override the iac source

# The Lambda function source repo for this environment
lambda_repo: https://github.com/tstrall/aws-lambda.git
lambda_strict: false  # Allows use of alternate Lambda sources
