# aws-config/environment/prod.yaml

name: prod

# The Git repo and branch where this account's config should be pulled from
config_repo: https://github.com/tstrall/aws-config.git
config_branch: main

# The Terraform module source repo for this environment
iac_repo: https://github.com/tstrall/aws-iac.git
iac_strict: true  # Lock to approved infrastructure modules only

# The Lambda function source repo for this environment
lambda_repo: https://github.com/tstrall/aws-lambda.git
lambda_strict: true  # Lock to approved Lambda functions only
